name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Lua 5.4.7
      run: |
        wget https://www.lua.org/ftp/lua-5.4.7.tar.gz
        tar zxpf lua-5.4.7.tar.gz
        cd lua-5.4.7
        make linux test
        sudo make install

    - name: Set up LuaJIT
      run: |
        sudo apt-get update
        sudo apt-get install -y luajit libluajit-5.1-dev

    - name: Set up OpenResty
      run: |
        wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
        sudo apt-get update
        sudo apt-get install -y openresty

    - name: Set up LuaRocks
      run: |
        wget https://luarocks.github.io/luarocks/releases/luarocks-3.11.1.tar.gz
        tar zxpf luarocks-3.11.1.tar.gz
        cd luarocks-3.11.1
        ./configure --with-lua-include=/usr/include/luajit-2.1
        make
        sudo make install

    - name: Install Lua dependencies
      run: |
        sudo luarocks install lapis
        sudo luarocks install lunamark
        sudo luarocks install lpeg
        sudo luarocks install luafilesystem

    - name: Start Lapis server
      run: |
        nohup lapis server &
        echo $! > lapis.pid

    - name: Generate static files
      run: |
        BUILD_DIR="build"
        echo "Cleaning build directory..."
        rm -rf $BUILD_DIR/*
        mkdir -p $BUILD_DIR

        echo "Downloading static files..."
        wget --mirror --convert-links --adjust-extension --page-requisites --no-parent http://localhost:8080 -P $BUILD_DIR

        echo "Organizing downloaded files..."
        mv $BUILD_DIR/localhost:8080/* $BUILD_DIR/
        rm -rf $BUILD_DIR/localhost:8080

        echo "Download complete. Static files are in the $BUILD_DIR directory."

    - name: Stop Lapis server
      run: |
        kill $(cat lapis.pid)

    - name: Add CNAME file
      run: |
        echo "lizz.dev" > build/CNAME

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
